### ISSUE TITLE
Canada - Quebec/Ontario - New Gauge Source

### ISSUE THREAD

**Issue by Lunatyc82** [whitewater-guide/gorge#19]
http://ottawariver.ca/conditions/

This is a new source for Gauges along the Ontario/Quebec divide. which is the end river for a catchment of 146 000 km².

Specifically the " GATINEAU RIVER AT MANIWAKI " will be used to measure a busy section of river with one of the best surf waves in the world.

**Comment by doomsower** [comment]
> The data provided by this web service may not be reproduced or redistributed.

Hmm. Mike will contact them.
